source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

# Exclude problematic versions of cocoapods and activesupport that caused
# historical build failures. The xcodeproj/concurrent-ruby ceilings were
# needed for older Ruby + CocoaPods stacks; modern stacks (Ruby 3.1+ with
# CocoaPods 1.16+) don't need them and keeping them forces bundler to resolve
# mismatched versions that conflict with Podfile.lock.
gem 'cocoapods', '>= 1.16', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'

# Ruby 3.4.0 removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
gem 'tsort'
